#!/bin/sh
# Set factory MAC addresses dynamically on first boot for LAN and WAN.
. /lib/functions.sh
. /lib/functions/system.sh

BASE_MAC=$(mtd_get_mac_binary Config 0x4)
if [ -z "$BASE_MAC" ] || [ "$BASE_MAC" = "00:00:00:00:00:00" ] || [ "$BASE_MAC" = "ff:ff:ff:ff:ff:ff" ]; then
	BASE_MAC=$(cat /sys/class/net/eth0/address 2>/dev/null)
fi

case "$BASE_MAC" in
	"" | 00:00:00:00:00:00 | ff:ff:ff:ff:ff:ff)
		exit 0
		;;
esac

WAN_MAC="$BASE_MAC"
LAN_MAC=$(macaddr_add "$BASE_MAC" 1)

uci -q batch <<EOF
set network.@device[0].macaddr='$LAN_MAC'
set network.wan.macaddr='$WAN_MAC'
commit network
EOF

logger -t factory-mac "Applied factory MACs: WAN=$WAN_MAC, LAN=$LAN_MAC"
exit 0
