#!/bin/sh
# Set factory MAC addresses dynamically on first boot for LAN, WAN, and Wireless.
. /lib/functions.sh
. /lib/functions/system.sh

BASE_MAC=$(mtd_get_mac_binary Config 0x4)
if [ -z "$BASE_MAC" ] || [ "$BASE_MAC" = "00:00:00:00:00:00" ] || [ "$BASE_MAC" = "ff:ff:ff:ff:ff:ff" ]; then
	BASE_MAC=$(mtd_get_mac_binary Config 0x20004)
fi
if [ -z "$BASE_MAC" ] || [ "$BASE_MAC" = "00:00:00:00:00:00" ] || [ "$BASE_MAC" = "ff:ff:ff:ff:ff:ff" ]; then
	BASE_MAC=$(mtd_get_mac_binary Factory 0x4)
fi
if [ -z "$BASE_MAC" ] || [ "$BASE_MAC" = "00:00:00:00:00:00" ] || [ "$BASE_MAC" = "ff:ff:ff:ff:ff:ff" ]; then
	BASE_MAC=$(cat /sys/class/net/eth0/address 2>/dev/null)
fi

case "$BASE_MAC" in
	"" | 00:00:00:00:00:00 | ff:ff:ff:ff:ff:ff)
		exit 0
		;;
esac

WAN_MAC="$BASE_MAC"
LAN_MAC=$(macaddr_add "$BASE_MAC" 1)
WIFI24_MAC=$(macaddr_add "$BASE_MAC" 2)
WIFI5_MAC=$(macaddr_add "$BASE_MAC" 3)

uci -q batch <<EOF
set network.@device[0].macaddr='$LAN_MAC'
set network.wan.macaddr='$WAN_MAC'
set wireless.default_radio0.macaddr='$WIFI24_MAC'
set wireless.default_radio1.macaddr='$WIFI5_MAC'
commit network
commit wireless
EOF

logger -t factory-mac "Applied factory MACs: WAN=$WAN_MAC, LAN=$LAN_MAC, 2.4G=$WIFI24_MAC, 5G=$WIFI5_MAC"
exit 0
