#!/bin/sh
# Enable MT7621 Hardware PPE NAT Offloading and Multi-Thread SMP Service
uci -q batch <<EOF
set firewall.@defaults[0].flow_offloading='1'
set firewall.@defaults[0].flow_offloading_hw='1'
commit firewall
EOF

# Enable smp_tuning service
[ -x /etc/init.d/smp_tuning ] && /etc/init.d/smp_tuning enable

exit 0
