#!/bin/sh
/etc/init.d/horus_client stop
/etc/init.d/horus_client disable
# Remove injected horus_augment.js from theme headers
for h in /usr/lib/lua/luci/view/themes/*/header.htm; do
    [ -f "$h" ] && sed -i '/horus_augment.js/d' "$h"
done
# Restore stock strict Hostname validation (undo the Arabic-hostname relax)
for f in /www/luci-static/resources/view/system/system.js.horus-orig /usr/lib/lua/luci/model/cbi/admin_system/system.lua.horus-orig; do
    [ -f "$f" ] && mv -f "$f" "${f%.horus-orig}"
done
rm -rf /tmp/luci-* 2>/dev/null
exit 0
