#!/bin/sh
. /usr/lib/horus/cgi_auth.sh || exit 1
horus_require_auth read
printf "Content-Type: application/json\r\n"
printf "Cache-Control: no-cache\r\n"
printf "\r\n"

PEER_FILE="/tmp/horus_ap_peers.json"

if [ -f "$PEER_FILE" ] && [ -s "$PEER_FILE" ]; then
    cat "$PEER_FILE"
else
    printf '{}'
fi
